---
- name: Install and configure web servers
  hosts: webservers
  gather_facts: true
  become: true
  tags: webservers
  tasks:
    - name: Wait until apt lock is released
      shell: |
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for other apt process to finish..."
          sleep 20
        done
      register: apt_wait_result
      changed_when: false
      
    - name: Update cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 7200
    - name: Ensure SNMP config directory exists
      file:
        path: /etc/snmp
        state: directory
        mode: '0755'

    - name: Copy snmpd.conf
      copy:
        src: templete_files/snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf

    - name: Restart snmpd
      service:
        name: snmpd
        state: restarted

    - name: Create a directory for the web server
      file: 
        path: /home/ubuntu/flask
        state: directory
        mode: '0755'

    - name: Copy the Flask app
      copy:
        src: templete_files/application2.py
        dest: /home/ubuntu/flask/app.py

    - name: Copy the Flask service file
      template:
        src: templete_files/flask.service.j2
        dest: /etc/systemd/system/flask.service

    - name: Start the Flask service
      systemd:
        name: flask
        state: started
        enabled: true

- name: Gather facts on all hosts
  hosts: webservers
  gather_facts: true
  tags: gather_facts
  tasks: []

- name: Configure HAProxy and Nginx
  hosts: haproxy
  gather_facts: true
  become: true
  tags: haproxy
  tasks:
    - name: Configure HAProxy
      template:
        src: templete_files/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Restart HAProxy

    - name: Configure Nginx
      template:
        src: templete_files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

